/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dashboard": [],
    "users.search": [],
    "users.index": [],
    "users.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.delete": [
        {
            "name": "id",
            "required": true
        }
    ]
}
}
export {};
